CREATE TABLE EMPLEADOS_IOT
   (	EMPLEADO_ID NUMBER,
	NOMBRE VARCHAR2(100),
	APELLIDO VARCHAR2(100),
	EMAIL VARCHAR2(100),
	 CONSTRAINT PK_EMPLEADOS_IOT PRIMARY KEY (EMPLEADO_ID) ENABLE
   ) ORGANIZATION INDEX NOCOMPRESS ;

